services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: madebymackratt
      WORDPRESS_DB_PASSWORD: fUzuXdch5zu78v
      WORDPRESS_DB_NAME: madebymackratt
    volumes:
      - ./wordpress:/var/www/html

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: madebymackratt
      MYSQL_USER: madebymackratt
      MYSQL_PASSWORD: fUzuXdch5zu78v
      MYSQL_ROOT_PASSWORD: 6hMzmeWw5hEuD3
    volumes:
      - ./mysql:/var/lib/mysql

networks: 
  default: 
    name: default-ext