services:
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://www.bobbitt.dev/vault
    volumes:
      - ./vaultwarden:/data

  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    restart: unless-stopped
    user: '1001'
    volumes:
      - ./gitea/data:/var/lib/gitea
      - ./gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./jellyfin:/config
      - /mnt/hdd/merged/media:/media

  flood:
    image: jesec/flood
    container_name: flood
    restart: unless-stopped
    command: --port 3000 --allowedpath /data --baseuri=/flood
    user: 1000:1000
    environment:
      HOME: /config
    volumes:
      - ./torrent:/config
      - /mnt/hdd/merged/raw:/data

  rtorrent:
    image: jesec/rtorrent
    container_name: rtorrent
    restart: unless-stopped
    command: -o network.port_range.set=6881-6881,system.daemon.set=true
    user: 1000:1000
    environment:
      HOME: /config
    network_mode: container:vpn
    volumes:
      - ./torrent:/config
      - /mnt/hdd/merged/raw:/data

  mrstech:
    build: ./mrstech
    image: avery/mrstech:latest
    container_name: mrstech
    restart: unless-stopped
    environment:
      - TOKEN=NDg5ODgyOTgzNTQ1NzAwMzUy.W5q9FA.y8DMUpGjWJOeU0BN_3Y6K9DPU3M
      - CLIENT_ID=489882983545700352
      - GUILD_ID=265926866014044161

networks: 
  default: 
    name: default-ext